<?php /** @var $block \MageSuite\ContentConstructorAdmin\Block\Adminhtml\Component\HeroCarousel */ ?>
<hero-carousel-configurator
    class="cc-hero-carousel-configurator <?=$block->getClasses()?>"
    :configuration="initialComponentConfiguration"
    :uploader-base-url="uploaderUrl"
    :assets-src="assetsSrc"
    :image-endpoint="imageEndpoint"
    :admin-prefix="adminPrefix"
    :cc-config="ccConfig"
></hero-carousel-configurator>
