<?php
/** @var $block \MageSuite\ContentConstructorAdmin\Block\Adminhtml\Component\Paragraph */
$wysiwygConfig = $block->getWysiwygConfig()->toArray();
?>
<paragraph-configurator
    class="cc-paragraph-configurator <?=$block->getClasses()?>"
    :configuration="initialComponentConfiguration"
    :rest-token="restToken"
    wysiwyg-config='<?=str_replace("'", "&#39;", json_encode($wysiwygConfig))?>'
    :uploader-base-url="uploaderUrl"
    :admin-prefix="adminPrefix"
    :assets-url="assetsSrc"
></paragraph-configurator>
