<?php /** @var $block \MageSuite\ContentConstructorAdmin\Block\Adminhtml\Component\ProductGridTeasers */ ?>
<magento-product-grid-teasers-configurator
    class="cc-magento-product-grid-teasers-configurator <?=$block->getClasses()?>"
    :configuration="initialComponentConfiguration"
    :uploader-base-url="uploaderUrl"
    :assets-src="assetsSrc"
    :image-endpoint="imageEndpoint"
    :cc-config="ccConfig"
    :products-per-page="productsPerPage"
    :admin-prefix="adminPrefix"
></magento-product-grid-teasers-configurator>
