<?php
/** @var $block \MageSuite\ContentConstructorAdmin\Block\Adminhtml\Component\StaticBlock */
$blocks = $block->getBlocks();
?>
<template id="cc-static-block-template">
    <div class="cc-static-block-configurator">
        <section class="cc-static-block-configurator__section" v-if="ccConfig.static_block != null && ccConfig.static_block.custom_sections != null" v-for="section in ccConfig.static_block.custom_sections">
            <h3 class="cc-static-block-configurator__subtitle" v-if="section.label">{{section.label | translate}}</h3>
            <div class="cc-custom-fields">
                <div class="cc-custom-fields__form-group" v-for="field in section.content.fields">
                    <component
                        :is="'custom-element-' + field.type"
                        :configuration="configuration"
                        :field-configuration="field"
                    ></component>
                </div>
            </div>
        </section>

        <section class="cc-static-block-configurator__section">
            <h3 class="cc-static-block-configurator__subtitle">Configuration</h3>
            <form class="cc-static-block-configurator__form" @submit.prevent="onSave">
                <div class="cc-input cc-input--type-inline">
                    <label for="cfg-static-block" class="cc-input__label">Static Block:</label>
                    <select name="select" class="cc-input__select" id="cfg-static-block" v-model="configuration.identifier"  v-el:cms-blocks-select @change="onChange">
                        <option value="">-- <?=__('Select CMS Block')?> --</option>
                        <?php foreach($blocks as $block): ?>
                            <option value="<?=$block['identifier']?>"><?=$block['title']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="cc-input cc-input--type-inline">
                    <label for="cfg-resetstyles" class="cc-input__label"><?=__('Reset default styles of CMS Static Block')?></label>
                    <div class="admin__actions-switch" data-role="switcher">
                        <input type="checkbox" class="admin__actions-switch-checkbox" id="cfg-resetstyles" name="reset_default_styles_of_cms" v-model="configuration.resetstyles" @change="onChange">
                        <label class="admin__actions-switch-label" for="cfg-resetstyles">
                            <span class="admin__actions-switch-text" data-text-on="Yes" data-text-off="No"></span>
                        </label>
                    </div>
                </div>
            </form>
        </section>
    </div>
</template>

<static-block-configurator class="cc-static-block-configurator" :configuration="initialComponentConfiguration" :cc-config="ccConfig"></static-block-configurator>
