<?php /** @var $block \MageSuite\ContentConstructorAdmin\Block\Adminhtml\Component\Icon */ ?>
<teaser-and-text-configurator
    class="cc-teaser-and-text-configurator <?=$block->getClasses()?>"
    :configuration="initialComponentConfiguration"
    :uploader-base-url="uploaderUrl"
    :image-endpoint="imageEndpoint"
    :admin-prefix="adminPrefix"
    :cc-config="ccConfig"
></teaser-and-text-configurator>
