<?php /** @var $block \MageSuite\ContentConstructorAdmin\Block\Adminhtml\ContentConstructor\AbstractConstructor */ ?>
<m2c-content-constructor
        configurator-endpoint="<?= $block->getConfiguratorEndpointUrl() ?>"
        configuration='<?= str_replace("'", "&#39;", $block->resolveConfigurationMedia($block->getExistingComponentsConfiguration())) ?>'
        configuration-dump="input[name=components]"
        assets-src="<?= $block->getAsset('/') ?>/"
        uploader-url="<?= $block->getUploaderUrl() ?>"
        rest-token-endpoint="<?= $block->getRestTokenEndpoint() ?>"
        image-endpoint="<?= $block->getImageEndpoint() ?>"
        category-data-provider-endpoint="<?= $block->getCategoryDataProviderEndpoint() ?>"
        page-type="<?= $block->getPageType() ?>"
        cc-configuration='<?= str_replace("'", "&#39;", $block->getContentConstructorConfig()) ?>'
        cc-project-configuration='<?= str_replace("'", "&#39;", $block->getProjectConfig()) ?>'
        cc-creativeshop-configuration='<?= str_replace("'", "&#39;", $block->getCreativeshopConfig()) ?>'
        products-per-page='<?= $block->getProductsPerPage() ?>'
        admin-prefix="<?= $block->getAdminPrefix() ?>"
        sorters='<?= str_replace("'", "&#39;", $block->getSorters()) ?>'
        filters='<?= str_replace("'", "&#39;", $block->getFilters()) ?>'
>
</m2c-content-constructor>


<script>
    (function (doc) {
        var scripts = doc.getElementsByTagName('script');
        var script = scripts[scripts.length - 1];
        var xhr = new XMLHttpRequest();
        xhr.onload = function () {
            var div = doc.createElement('div');
            div.innerHTML = this.responseText;
            div.style.width = div.style.height = 0;
            div.style.position = 'absolute';
            div.style.overflow = 'hidden';
            script.parentNode.insertBefore(div, script);
        };
        xhr.open('get', '<?=$block->getAsset('/images/sprites.svg');?>', true);
        xhr.send();
    })(document)
    // Initialize content constructor using AMD.
    require([
        'jquery',
        'Vue',
        'VueResource',
        'm2cContentConstructor',
        'Magento_Ui/js/modal/modal',
        'mage/adminhtml/wysiwyg/tiny_mce/setup',
        'mage/adminhtml/wysiwyg/widget',
        'loadingPopup'
    ], function ($, Vue, VueResource, m2cContentConstructor, modal) {
        new Vue({
            el: 'body',
            components: {
                'm2c-content-constructor': m2cContentConstructor
            }
        });
    });
</script>

<script>
    function previewContentConstructor(json) {
        requirejs(['jquery'], function ($) {
            var $newForm = $('<form>', {
                'action': '/content-constructor/preview/view',
                'target': '_blank',
                'method': 'POST'
            }).append($('<input>', {
                'name': 'configuration',
                'value': json,
                'type': 'hidden'
            }));

            $(document.body).append($newForm);

            $newForm.submit();
        })
    }

    csWysiwygEditor = undefined;

    openEditorPopup = function(url, name, specs, parent) {
        if ((typeof popups == "undefined") || popups[name] == undefined || popups[name].closed) {
            if (typeof popups == "undefined") {
                popups = new Array();
            }
            var opener = (parent != undefined ? parent : window);
            popups[name] = opener.open(url, name, specs);
        } else {
            popups[name].focus();
        }
        return popups[name];
    }

    closeEditorPopup = function(name) {
        if ((typeof popups != "undefined") && popups[name] != undefined && !popups[name].closed) {
            popups[name].close();
        }
    }
</script>
